server:
  port: 8081
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/addressservicedb
    username: postgres
    password: root123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest 


# actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:  # for eureka server
      enabled: true
  info:
    env:
      enabled: true


endpoints:
  shutdown:
    enabled: true

#information above this instance
info:
  app:
    name: "Address Service"
    description: "Address Service With Food Order System"
    version: "1.0.0"
 
# for eureka server
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8073/eureka/