server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/addressservicedb
    username: postgres
    password: root123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest 
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  


# actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:  # for eureka server
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


endpoints:
  shutdown:
    enabled: true

#information above this instance
info:
  app:
    name: "Address Service"
    description: "Address Service With Food Order System"
    version: "1.0.0"
 
# for eureka server
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8073/eureka/



logging:
  level:
    com:
      food:
        app: DEBUG

  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"


resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
