server:
  port: 8074
 

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      httpclient:
        # time out configration as yml file
        connect-timeout: 1000
        response-timeout: 10s
      discovery:
        locator:
          enabled: true
          all-namespaces: true
          lowerCaseServiceId: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest 


springdoc:
  swagger-ui:
    path: /
    enabled: true
    urls:
      - name: user
        url: user/v3/api-docs
      - name: department
        url: /v3/api-docs/department
      - name: organization
        url: /v3/api-docs/organization

  enable-native-support: true
  api-docs:
    enabled: true


#enable all actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # for all actuator property
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true


info:
  app:
    name: "gateway server"
    description: "Food Order System  gateway server"
    version: "1.0.0"


logging:
  level:
    com:
      gateway:
        sever: DEBUG
    org:
      springframework:
        cloud:
          gateway: DEBUG
        http:
          server:
            reactive: DEBUG
        web:
          reactive: DEBUG
        
    
    
# for eureka server
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8073/eureka/
